param(
  [switch]$Build
)

# aplicar-v100b-corrigir-header-operador.ps1
# Corrige o header da tela /operator/dashboard:
# - Usa o logo Astro Ingressos em imagem.
# - Usa altura e estilo parecido com o CustomerHeader.
# - Troca o botao "Tela principal" solto por menu com hamburguer/avatar.
# - Menu mostra Operadores, Tela principal e Sair.

$ErrorActionPreference = "Stop"

$Root = Get-Location
$Stamp = Get-Date -Format "yyyyMMdd-HHmmss"

$PanelPath = Join-Path $Root "apps\web\src\app\operator\_components\OperatorPanel.tsx"
$WebDir = Join-Path $Root "apps\web"

function Write-Utf8($Path, $Content) {
  $Dir = Split-Path $Path -Parent
  if (-not (Test-Path $Dir)) {
    New-Item -ItemType Directory -Path $Dir -Force | Out-Null
  }

  $Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $Content, $Utf8NoBom)
}

Write-Host "Aplicando v100b - corrigir header do operador..." -ForegroundColor Cyan

if (-not (Test-Path $PanelPath)) {
  throw "Nao encontrei apps\web\src\app\operator\_components\OperatorPanel.tsx"
}

$Backup = "$PanelPath.bak-v100b-$Stamp"
Copy-Item $PanelPath $Backup -Force
Write-Host "Backup criado: $Backup" -ForegroundColor DarkGray

$PatchPath = Join-Path $env:TEMP "v100b-corrigir-header-operador.js"
$Patch = [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("Y29uc3QgZnMgPSByZXF1aXJlKCJmcyIpOwoKY29uc3QgZmlsZVBhdGggPSBwcm9jZXNzLmFyZ3ZbMl07CmxldCBzb3VyY2UgPSBmcy5yZWFkRmlsZVN5bmMoZmlsZVBhdGgsICJ1dGY4Iik7CgpmdW5jdGlvbiBmaW5kRnVuY3Rpb25CbG9jayhuYW1lKSB7CiAgY29uc3Qgc3RhcnQgPSBzb3VyY2UuaW5kZXhPZihgZnVuY3Rpb24gJHtuYW1lfWApOwogIGlmIChzdGFydCA8IDApIHJldHVybiBudWxsOwogIGNvbnN0IG9wZW4gPSBzb3VyY2UuaW5kZXhPZigieyIsIHN0YXJ0KTsKICBpZiAob3BlbiA8IDApIHJldHVybiBudWxsOwoKICBsZXQgZGVwdGggPSAwOwogIGxldCBxdW90ZSA9IG51bGw7CiAgbGV0IGVzY2FwaW5nID0gZmFsc2U7CiAgbGV0IGxpbmVDb21tZW50ID0gZmFsc2U7CiAgbGV0IGJsb2NrQ29tbWVudCA9IGZhbHNlOwoKICBmb3IgKGxldCBpID0gb3BlbjsgaSA8IHNvdXJjZS5sZW5ndGg7IGkgKz0gMSkgewogICAgY29uc3QgY2ggPSBzb3VyY2VbaV07CiAgICBjb25zdCBuZXh0ID0gc291cmNlW2kgKyAxXTsKCiAgICBpZiAobGluZUNvbW1lbnQpIHsKICAgICAgaWYgKGNoID09PSAiXG4iKSBsaW5lQ29tbWVudCA9IGZhbHNlOwogICAgICBjb250aW51ZTsKICAgIH0KCiAgICBpZiAoYmxvY2tDb21tZW50KSB7CiAgICAgIGlmIChjaCA9PT0gIioiICYmIG5leHQgPT09ICIvIikgewogICAgICAgIGJsb2NrQ29tbWVudCA9IGZhbHNlOwogICAgICAgIGkgKz0gMTsKICAgICAgfQogICAgICBjb250aW51ZTsKICAgIH0KCiAgICBpZiAocXVvdGUpIHsKICAgICAgaWYgKGVzY2FwaW5nKSB7CiAgICAgICAgZXNjYXBpbmcgPSBmYWxzZTsKICAgICAgICBjb250aW51ZTsKICAgICAgfQogICAgICBpZiAoY2ggPT09ICJcXCIpIHsKICAgICAgICBlc2NhcGluZyA9IHRydWU7CiAgICAgICAgY29udGludWU7CiAgICAgIH0KICAgICAgaWYgKHF1b3RlID09PSAiYCIgJiYgY2ggPT09ICIkIiAmJiBuZXh0ID09PSAieyIpIHsKICAgICAgICBkZXB0aCArPSAxOwogICAgICAgIGkgKz0gMTsKICAgICAgICBjb250aW51ZTsKICAgICAgfQogICAgICBpZiAoY2ggPT09IHF1b3RlKSBxdW90ZSA9IG51bGw7CiAgICAgIGNvbnRpbnVlOwogICAgfQoKICAgIGlmIChjaCA9PT0gIi8iICYmIG5leHQgPT09ICIvIikgewogICAgICBsaW5lQ29tbWVudCA9IHRydWU7CiAgICAgIGkgKz0gMTsKICAgICAgY29udGludWU7CiAgICB9CgogICAgaWYgKGNoID09PSAiLyIgJiYgbmV4dCA9PT0gIioiKSB7CiAgICAgIGJsb2NrQ29tbWVudCA9IHRydWU7CiAgICAgIGkgKz0gMTsKICAgICAgY29udGludWU7CiAgICB9CgogICAgaWYgKGNoID09PSAnIicgfHwgY2ggPT09ICInIiB8fCBjaCA9PT0gImAiKSB7CiAgICAgIHF1b3RlID0gY2g7CiAgICAgIGNvbnRpbnVlOwogICAgfQoKICAgIGlmIChjaCA9PT0gInsiKSBkZXB0aCArPSAxOwogICAgaWYgKGNoID09PSAifSIpIHsKICAgICAgZGVwdGggLT0gMTsKICAgICAgaWYgKGRlcHRoID09PSAwKSByZXR1cm4geyBzdGFydCwgZW5kOiBpICsgMSB9OwogICAgfQogIH0KCiAgcmV0dXJuIG51bGw7Cn0KCmNvbnN0IHRvcGJhciA9IGBmdW5jdGlvbiBUb3BiYXIoeyB1c2VyIH06IHsgdXNlcjogU3RvcmVkVXNlciB8IG51bGwgfSkgewogIGNvbnN0IFttZW51T3Blbiwgc2V0TWVudU9wZW5dID0gdXNlU3RhdGUoZmFsc2UpOwoKICBjb25zdCByb2xlID0gU3RyaW5nKHVzZXI/LnJvbGUgfHwgIk9QRVJBVE9SIikudG9VcHBlckNhc2UoKTsKICBjb25zdCBzb3VyY2UgPSBTdHJpbmcodXNlcj8ubmFtZSB8fCB1c2VyPy5lbWFpbCB8fCAiTyIpLnRyaW0oKTsKICBjb25zdCBwaWVjZXMgPSBzb3VyY2Uuc3BsaXQoL1xccysvKS5maWx0ZXIoQm9vbGVhbik7CiAgY29uc3QgaW5pdGlhbHMgPQogICAgcGllY2VzLmxlbmd0aCA8PSAxCiAgICAgID8gc291cmNlLnNsaWNlKDAsIDEpLnRvVXBwZXJDYXNlKCkKICAgICAgOiBcYFwke3BpZWNlc1swXS5zbGljZSgwLCAxKX1cJHtwaWVjZXNbcGllY2VzLmxlbmd0aCAtIDFdLnNsaWNlKDAsIDEpfVxgLnRvVXBwZXJDYXNlKCk7CgogIGZ1bmN0aW9uIGhhbmRsZUxvZ291dCgpIHsKICAgIGxvY2FsU3RvcmFnZS5yZW1vdmVJdGVtKCJ0b2tlbiIpOwogICAgbG9jYWxTdG9yYWdlLnJlbW92ZUl0ZW0oInJlZnJlc2hUb2tlbiIpOwogICAgbG9jYWxTdG9yYWdlLnJlbW92ZUl0ZW0oInVzZXIiKTsKICAgIHdpbmRvdy5sb2NhdGlvbi5hc3NpZ24oIi9sb2dpbiIpOwogIH0KCiAgcmV0dXJuICgKICAgIDxoZWFkZXIgY2xhc3NOYW1lPSJzdGlja3kgdG9wLTAgei1bOTk5OV0gYm9yZGVyLWIgYm9yZGVyLVsjZWE1ZjAwXSBiZy1bI2ZmNjkwMF0gc2hhZG93LXNtIj4KICAgICAgPGRpdiBjbGFzc05hbWU9Im14LWF1dG8gZmxleCBoLVs4MnB4XSBtYXgtdy1bMTE4MHB4XSBpdGVtcy1jZW50ZXIgZ2FwLTUgcHgtNCI+CiAgICAgICAgPGEgaHJlZj0iL2Rhc2hib2FyZCIgY2xhc3NOYW1lPSJmbGV4IHNocmluay0wIGl0ZW1zLWNlbnRlciIgYXJpYS1sYWJlbD0iQXN0cm8gSW5ncmVzc29zIj4KICAgICAgICAgIDxpbWcKICAgICAgICAgICAgc3JjPSIvYXN0cm8taW5ncmVzc29zLWxvZ28ucG5nIgogICAgICAgICAgICBhbHQ9IkFzdHJvIEluZ3Jlc3NvcyIKICAgICAgICAgICAgY2xhc3NOYW1lPSJoLVs1NnB4XSB3LWF1dG8gb2JqZWN0LWNvbnRhaW4iCiAgICAgICAgICAvPgogICAgICAgIDwvYT4KCiAgICAgICAgPGRpdiBjbGFzc05hbWU9ImZsZXgtMSIgLz4KCiAgICAgICAgPGRpdiBjbGFzc05hbWU9InJlbGF0aXZlIHNocmluay0wIj4KICAgICAgICAgIDxidXR0b24KICAgICAgICAgICAgdHlwZT0iYnV0dG9uIgogICAgICAgICAgICBvbkNsaWNrPXsoKSA9PiBzZXRNZW51T3BlbigodmFsdWUpID0+ICF2YWx1ZSl9CiAgICAgICAgICAgIGNsYXNzTmFtZT0iZmxleCBoLTExIGl0ZW1zLWNlbnRlciBnYXAtMiByb3VuZGVkLWZ1bGwgYmctd2hpdGUgcHgtMyB0ZXh0LVsjMTkwMDJmXSBzaGFkb3ctc20gcmluZy0xIHJpbmctYmxhY2svMTAiCiAgICAgICAgICAgIGFyaWEtbGFiZWw9IkFicmlyIG1lbnUiCiAgICAgICAgICA+CiAgICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT0idGV4dC14bCBsZWFkaW5nLW5vbmUiPuKYsDwvc3Bhbj4KICAgICAgICAgICAgPHNwYW4gY2xhc3NOYW1lPSJmbGV4IGgtOCB3LTggaXRlbXMtY2VudGVyIGp1c3RpZnktY2VudGVyIHJvdW5kZWQtZnVsbCBiZy1bIzE5MDAyZl0gdGV4dC1zbSBmb250LWJsYWNrIHRleHQtd2hpdGUiPgogICAgICAgICAgICAgIHtpbml0aWFscyB8fCAiTyJ9CiAgICAgICAgICAgIDwvc3Bhbj4KICAgICAgICAgIDwvYnV0dG9uPgoKICAgICAgICAgIHttZW51T3BlbiA/ICgKICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImFic29sdXRlIHJpZ2h0LTAgei1bMTAwMDBdIG10LTMgdy04MCBvdmVyZmxvdy1oaWRkZW4gcm91bmRlZC0yeGwgYm9yZGVyIGJvcmRlci1uZXV0cmFsLTIwMCBiZy13aGl0ZSBzaGFkb3cteGwiPgogICAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJib3JkZXItYiBib3JkZXItbmV1dHJhbC0xMDAgcHgtNCBweS00Ij4KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJmbGV4IGl0ZW1zLXN0YXJ0IGp1c3RpZnktYmV0d2VlbiBnYXAtMyI+CiAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJtaW4tdy0wIj4KICAgICAgICAgICAgICAgICAgICA8cCBjbGFzc05hbWU9InRydW5jYXRlIHRleHQtc20gZm9udC1ibGFjayB0ZXh0LW5ldXRyYWwtOTUwIj4KICAgICAgICAgICAgICAgICAgICAgIHt1c2VyPy5uYW1lIHx8ICJPcGVyYWRvciJ9CiAgICAgICAgICAgICAgICAgICAgPC9wPgogICAgICAgICAgICAgICAgICAgIDxwIGNsYXNzTmFtZT0ibXQtMSBicmVhay1hbGwgdGV4dC14cyBmb250LXNlbWlib2xkIHRleHQtbmV1dHJhbC01MDAiPgogICAgICAgICAgICAgICAgICAgICAge3VzZXI/LmVtYWlsIHx8ICJzZW0gZS1tYWlsIn0KICAgICAgICAgICAgICAgICAgICA8L3A+CiAgICAgICAgICAgICAgICAgICAgPHAgY2xhc3NOYW1lPSJtdC0xIHRleHQteHMgdGV4dC1uZXV0cmFsLTQwMCI+CiAgICAgICAgICAgICAgICAgICAgICBDUEY6IHt1c2VyPy5jcGYgfHwgIm7Do28gaW5mb3JtYWRvIn0KICAgICAgICAgICAgICAgICAgICA8L3A+CiAgICAgICAgICAgICAgICAgIDwvZGl2PgoKICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3NOYW1lPSJyb3VuZGVkLWZ1bGwgYmctbmV1dHJhbC0xMDAgcHgtMiBweS0xIHRleHQtWzEwcHhdIGZvbnQtYmxhY2sgdXBwZXJjYXNlIHRyYWNraW5nLVswLjEyZW1dIHRleHQtbmV1dHJhbC01MDAiPgogICAgICAgICAgICAgICAgICAgIHtyb2xlfQogICAgICAgICAgICAgICAgICA8L3NwYW4+CiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9InB4LTIgcGItMiBwdC0xIj4KICAgICAgICAgICAgICAgIDxwIGNsYXNzTmFtZT0icHgtMiB0ZXh0LVsxMHB4XSBmb250LWJsYWNrIHVwcGVyY2FzZSB0cmFja2luZy1bMC4yMmVtXSB0ZXh0LW5ldXRyYWwtNDAwIj4KICAgICAgICAgICAgICAgICAgT3BlcmHDp8OjbwogICAgICAgICAgICAgICAgPC9wPgoKICAgICAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJtdC0yIHNwYWNlLXktMSI+CiAgICAgICAgICAgICAgICAgIDxhCiAgICAgICAgICAgICAgICAgICAgaHJlZj0iL29wZXJhdG9yL2Rhc2hib2FyZCIKICAgICAgICAgICAgICAgICAgICBjbGFzc05hbWU9ImZsZXggdy1mdWxsIGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWJldHdlZW4gcm91bmRlZC14bCBiZy1uZXV0cmFsLTk1MCBweC0zIHB5LTMgdGV4dC1sZWZ0IHRleHQtc20gZm9udC1zZW1pYm9sZCB0ZXh0LXdoaXRlIHRyYW5zaXRpb24iCiAgICAgICAgICAgICAgICAgID4KICAgICAgICAgICAgICAgICAgICA8c3Bhbj5PcGVyYWRvcmVzPC9zcGFuPgogICAgICAgICAgICAgICAgICA8L2E+CiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImJvcmRlci10IGJvcmRlci1uZXV0cmFsLTEwMCBwLTIiPgogICAgICAgICAgICAgICAgPGEKICAgICAgICAgICAgICAgICAgaHJlZj0iL2Rhc2hib2FyZCIKICAgICAgICAgICAgICAgICAgY2xhc3NOYW1lPSJmbGV4IHctZnVsbCBpdGVtcy1jZW50ZXIganVzdGlmeS1iZXR3ZWVuIHJvdW5kZWQteGwgcHgtMyBweS0zIHRleHQtbGVmdCB0ZXh0LXNtIGZvbnQtc2VtaWJvbGQgdGV4dC1uZXV0cmFsLTcwMCB0cmFuc2l0aW9uIGhvdmVyOmJnLW5ldXRyYWwtNTAgaG92ZXI6dGV4dC1uZXV0cmFsLTk1MCIKICAgICAgICAgICAgICAgID4KICAgICAgICAgICAgICAgICAgPHNwYW4+VGVsYSBwcmluY2lwYWw8L3NwYW4+CiAgICAgICAgICAgICAgICA8L2E+CgogICAgICAgICAgICAgICAgPGJ1dHRvbgogICAgICAgICAgICAgICAgICB0eXBlPSJidXR0b24iCiAgICAgICAgICAgICAgICAgIG9uQ2xpY2s9e2hhbmRsZUxvZ291dH0KICAgICAgICAgICAgICAgICAgY2xhc3NOYW1lPSJtdC0xIGZsZXggdy1mdWxsIGl0ZW1zLWNlbnRlciByb3VuZGVkLXhsIHB4LTMgcHktMyB0ZXh0LWxlZnQgdGV4dC1zbSBmb250LXNlbWlib2xkIHRleHQtcmVkLTYwMCBob3ZlcjpiZy1yZWQtNTAiCiAgICAgICAgICAgICAgICA+CiAgICAgICAgICAgICAgICAgIFNhaXIKICAgICAgICAgICAgICAgIDwvYnV0dG9uPgogICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICkgOiBudWxsfQogICAgICAgIDwvZGl2PgogICAgICA8L2Rpdj4KICAgIDwvaGVhZGVyPgogICk7Cn1gOwoKY29uc3QgYmxvY2sgPSBmaW5kRnVuY3Rpb25CbG9jaygiVG9wYmFyIik7CmlmICghYmxvY2spIHsKICB0aHJvdyBuZXcgRXJyb3IoIk5hbyBlbmNvbnRyZWkgZnVuY3Rpb24gVG9wYmFyIG5vIE9wZXJhdG9yUGFuZWwudHN4LiIpOwp9Cgpzb3VyY2UgPSBzb3VyY2Uuc2xpY2UoMCwgYmxvY2suc3RhcnQpICsgdG9wYmFyICsgc291cmNlLnNsaWNlKGJsb2NrLmVuZCk7Cgpmcy53cml0ZUZpbGVTeW5jKGZpbGVQYXRoLCBzb3VyY2UsICJ1dGY4Iik7CmNvbnNvbGUubG9nKCJPSzogVG9wYmFyIGRvIG9wZXJhZG9yIHBhZHJvbml6YWRvIGNvbSBsb2dvL21lbnUuIik7Cg=="))
Write-Utf8 $PatchPath $Patch

& node $PatchPath $PanelPath

if ($LASTEXITCODE -ne 0) {
  throw "Falha ao aplicar v100b. Envie o erro acima."
}

Write-Host "Header do operador atualizado." -ForegroundColor Green

if ($Build) {
  Write-Host ""
  Write-Host "Rodando build do WEB para validar..." -ForegroundColor Cyan
  Push-Location $WebDir
  & cmd.exe /d /s /c "npm run build"
  $BuildExit = $LASTEXITCODE
  Pop-Location

  if ($BuildExit -ne 0) {
    Write-Host ""
    Write-Host "A v100b foi aplicada, mas o build encontrou erro." -ForegroundColor Yellow
    Write-Host "Envie o erro completo. Nao rode scripts antigos por cima." -ForegroundColor Yellow
    exit $BuildExit
  }

  Write-Host "Build do WEB passou." -ForegroundColor Green
} else {
  Write-Host ""
  Write-Host "Build nao executado para nao bloquear por erros antigos de outras telas." -ForegroundColor Yellow
  Write-Host "Para validar depois, rode este script com -Build." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "OK FINAL v100b:" -ForegroundColor Green
Write-Host "- Header do operador padronizado." -ForegroundColor Green
Write-Host "- Logo Astro voltou no topo." -ForegroundColor Green
Write-Host "- Menu com hamburguer/avatar criado." -ForegroundColor Green
Write-Host "- Tela principal ficou dentro do menu." -ForegroundColor Green
Write-Host ""
Write-Host "Reinicie o WEB:" -ForegroundColor Cyan
Write-Host 'cd "C:\Users\march\OneDrive\Área de Trabalho\plataforma-ingressos\apps\web"' -ForegroundColor Cyan
Write-Host "npm run dev" -ForegroundColor Cyan
